
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-02T12:15:16-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "bff421579e0abe0bc03a1f7fcc7d405155ca6d8f",
 "version": "v1.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
