# Generated by Django 5.0.6 on 2024-06-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='max_value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='min_value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
