from libdaw.metronome import Beat

class AddLength:
    def __init__(self, value: Beat) -> None: ...
    @property
    def value(self) -> Beat: ...
class SubtractLength:
    def __init__(self, value: Beat) -> None: ...
    @property
    def value(self) -> Beat: ...
class MultiplyLength:
    def __init__(self, value: float) -> None: ...
    @property
    def value(self) -> float: ...
class Constant:
    def __init__(self, value: Beat) -> None: ...
    @property
    def value(self) -> Beat: ...
