# coding: utf-8

"""
    Anch.io

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Contact: opensource@anchio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from anchio.models.employment_status_enum import EmploymentStatusEnum

class TestEmploymentStatusEnum(unittest.TestCase):
    """EmploymentStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmploymentStatusEnum(self):
        """Test EmploymentStatusEnum"""
        # inst = EmploymentStatusEnum()

if __name__ == '__main__':
    unittest.main()
