# coding: utf-8

"""
    Anch.io

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Contact: opensource@anchio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from anchio.models.token_schema_token_type_enum import TokenSchemaTokenTypeEnum

class TestTokenSchemaTokenTypeEnum(unittest.TestCase):
    """TokenSchemaTokenTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenSchemaTokenTypeEnum(self):
        """Test TokenSchemaTokenTypeEnum"""
        # inst = TokenSchemaTokenTypeEnum()

if __name__ == '__main__':
    unittest.main()
