# coding: utf-8

"""
    Anch.io

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Contact: opensource@anchio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from anchio.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_update_accesses_api_v1_corp_accesses_bulk_update_post(self) -> None:
        """Test case for bulk_update_accesses_api_v1_corp_accesses_bulk_update_post

        Bulk Update Accesses
        """
        pass

    def test_bulk_update_contracts_api_v1_corp_contracts_bulk_update_post(self) -> None:
        """Test case for bulk_update_contracts_api_v1_corp_contracts_bulk_update_post

        Bulk Update Contracts
        """
        pass

    def test_bulk_update_employees_api_v1_corp_employees_bulk_update_post(self) -> None:
        """Test case for bulk_update_employees_api_v1_corp_employees_bulk_update_post

        Bulk Update Employees
        """
        pass

    def test_bulk_upsert_licenses_api_v1_auth_licenses_bulk_post(self) -> None:
        """Test case for bulk_upsert_licenses_api_v1_auth_licenses_bulk_post

        Bulk Upsert Licenses
        """
        pass

    def test_change_password_api_v1_auth_change_password_post(self) -> None:
        """Test case for change_password_api_v1_auth_change_password_post

        Change Password
        """
        pass

    def test_create_alert_api_v1_metering_alerts_post(self) -> None:
        """Test case for create_alert_api_v1_metering_alerts_post

        Create Alert
        """
        pass

    def test_create_api_key_integration_api_v1_auth_integrations_api_key_post(self) -> None:
        """Test case for create_api_key_integration_api_v1_auth_integrations_api_key_post

        Create Api Key Integration
        """
        pass

    def test_create_channel_api_v1_notifications_channels_post(self) -> None:
        """Test case for create_channel_api_v1_notifications_channels_post

        Create Channel
        """
        pass

    def test_create_checkout_session_api_v1_auth_subscription_create_checkout_session_post(self) -> None:
        """Test case for create_checkout_session_api_v1_auth_subscription_create_checkout_session_post

        Create Checkout Session
        """
        pass

    def test_create_key_api_v1_auth_key_post(self) -> None:
        """Test case for create_key_api_v1_auth_key_post

        Create Key
        """
        pass

    def test_create_metered_service_api_v1_metering_services_post(self) -> None:
        """Test case for create_metered_service_api_v1_metering_services_post

        Create Metered Service
        """
        pass

    def test_delete_alert_api_v1_metering_alerts_id_delete(self) -> None:
        """Test case for delete_alert_api_v1_metering_alerts_id_delete

        Delete Alert
        """
        pass

    def test_delete_api_key_integration_api_v1_auth_integrations_api_key_key_id_delete(self) -> None:
        """Test case for delete_api_key_integration_api_v1_auth_integrations_api_key_key_id_delete

        Delete Api Key Integration
        """
        pass

    def test_delete_channel_api_v1_notifications_channels_id_delete(self) -> None:
        """Test case for delete_channel_api_v1_notifications_channels_id_delete

        Delete Channel
        """
        pass

    def test_delete_metered_service_api_v1_metering_services_id_delete(self) -> None:
        """Test case for delete_metered_service_api_v1_metering_services_id_delete

        Delete Metered Service
        """
        pass

    def test_delete_oauth_token_api_v1_auth_integrations_oauth_id_delete(self) -> None:
        """Test case for delete_oauth_token_api_v1_auth_integrations_oauth_id_delete

        Delete Oauth Token
        """
        pass

    def test_destroy_key_api_v1_auth_key_id_delete(self) -> None:
        """Test case for destroy_key_api_v1_auth_key_id_delete

        Destroy Key
        """
        pass

    def test_exchange_plaid_token_api_v1_auth_plaid_exchange_token_get(self) -> None:
        """Test case for exchange_plaid_token_api_v1_auth_plaid_exchange_token_get

        Exchange Plaid Token
        """
        pass

    def test_feedback_api_v1_auth_feedback_post(self) -> None:
        """Test case for feedback_api_v1_auth_feedback_post

        Feedback
        """
        pass

    def test_get_accesses_api_v1_corp_accesses_get(self) -> None:
        """Test case for get_accesses_api_v1_corp_accesses_get

        Get Accesses
        """
        pass

    def test_get_company_api_v1_auth_me_company_company_id_get(self) -> None:
        """Test case for get_company_api_v1_auth_me_company_company_id_get

        Get Company
        """
        pass

    def test_get_contracts_api_v1_corp_contracts_get(self) -> None:
        """Test case for get_contracts_api_v1_corp_contracts_get

        Get Contracts
        """
        pass

    def test_get_departments_api_v1_corp_departments_get(self) -> None:
        """Test case for get_departments_api_v1_corp_departments_get

        Get Departments
        """
        pass

    def test_get_employee_api_v1_corp_employees_employee_id_get(self) -> None:
        """Test case for get_employee_api_v1_corp_employees_employee_id_get

        Get Employee
        """
        pass

    def test_get_employee_tool_report_api_v1_tools_tools_reports_usage_employee_employee_id_get(self) -> None:
        """Test case for get_employee_tool_report_api_v1_tools_tools_reports_usage_employee_employee_id_get

        Get Employee Tool Report
        """
        pass

    def test_get_employees_api_v1_corp_employees_get(self) -> None:
        """Test case for get_employees_api_v1_corp_employees_get

        Get Employees
        """
        pass

    def test_get_license_api_v1_auth_me_license_get(self) -> None:
        """Test case for get_license_api_v1_auth_me_license_get

        Get License
        """
        pass

    def test_get_my_employee_api_v1_corp_employees_me_get(self) -> None:
        """Test case for get_my_employee_api_v1_corp_employees_me_get

        Get My Employee
        """
        pass

    def test_get_oauth_url_api_v1_auth_integrations_oauth_provider_get(self) -> None:
        """Test case for get_oauth_url_api_v1_auth_integrations_oauth_provider_get

        Get Oauth Url
        """
        pass

    def test_get_public_tools_api_v1_tools_public_company_slug_get(self) -> None:
        """Test case for get_public_tools_api_v1_tools_public_company_slug_get

        Get Public Tools
        """
        pass

    def test_get_tool_api_v1_tools_tool_id_get(self) -> None:
        """Test case for get_tool_api_v1_tools_tool_id_get

        Get Tool
        """
        pass

    def test_get_tool_categories_api_v1_tools_categories_get(self) -> None:
        """Test case for get_tool_categories_api_v1_tools_categories_get

        Get Tool Categories
        """
        pass

    def test_get_tool_usage_report_api_v1_tools_tools_reports_usage_tool_id_get(self) -> None:
        """Test case for get_tool_usage_report_api_v1_tools_tools_reports_usage_tool_id_get

        Get Tool Usage Report
        """
        pass

    def test_get_tools_api_v1_tools_get(self) -> None:
        """Test case for get_tools_api_v1_tools_get

        Get Tools
        """
        pass

    def test_get_user_api_v1_auth_me_get(self) -> None:
        """Test case for get_user_api_v1_auth_me_get

        Get User
        """
        pass

    def test_health_check_api_v1_health_check_get(self) -> None:
        """Test case for health_check_api_v1_health_check_get

        Health Check
        """
        pass

    def test_list_alerts_api_v1_metering_alerts_get(self) -> None:
        """Test case for list_alerts_api_v1_metering_alerts_get

        List Alerts
        """
        pass

    def test_list_api_key_integrations_api_v1_auth_integrations_api_key_get(self) -> None:
        """Test case for list_api_key_integrations_api_v1_auth_integrations_api_key_get

        List Api Key Integrations
        """
        pass

    def test_list_bank_accounts_api_v1_corp_bank_accounts_get(self) -> None:
        """Test case for list_bank_accounts_api_v1_corp_bank_accounts_get

        List Bank Accounts
        """
        pass

    def test_list_company_roles_api_v1_auth_company_roles_get(self) -> None:
        """Test case for list_company_roles_api_v1_auth_company_roles_get

        List Company Roles
        """
        pass

    def test_list_keys_api_v1_auth_key_get(self) -> None:
        """Test case for list_keys_api_v1_auth_key_get

        List Keys
        """
        pass

    def test_list_licenses_api_v1_auth_licenses_get(self) -> None:
        """Test case for list_licenses_api_v1_auth_licenses_get

        List Licenses
        """
        pass

    def test_list_metered_services_api_v1_metering_services_get(self) -> None:
        """Test case for list_metered_services_api_v1_metering_services_get

        List Metered Services
        """
        pass

    def test_list_notification_channels_api_v1_notifications_channels_get(self) -> None:
        """Test case for list_notification_channels_api_v1_notifications_channels_get

        List Notification Channels
        """
        pass

    def test_list_notifications_api_v1_notifications_get(self) -> None:
        """Test case for list_notifications_api_v1_notifications_get

        List Notifications
        """
        pass

    def test_list_oauth_integrations_api_v1_auth_integrations_oauth_get(self) -> None:
        """Test case for list_oauth_integrations_api_v1_auth_integrations_oauth_get

        List Oauth Integrations
        """
        pass

    def test_list_slack_channels_api_v1_integrations_slack_channels_get(self) -> None:
        """Test case for list_slack_channels_api_v1_integrations_slack_channels_get

        List Slack Channels
        """
        pass

    def test_list_transactions_api_v1_corp_transactions_get(self) -> None:
        """Test case for list_transactions_api_v1_corp_transactions_get

        List Transactions
        """
        pass

    def test_plaid_create_token_api_v1_auth_plaid_create_token_get(self) -> None:
        """Test case for plaid_create_token_api_v1_auth_plaid_create_token_get

        Plaid Create Token
        """
        pass

    def test_post_access_request_api_v1_corp_accesses_post(self) -> None:
        """Test case for post_access_request_api_v1_corp_accesses_post

        Post Access Request
        """
        pass

    def test_post_employee_access_request_api_v1_corp_accesses_employee_post(self) -> None:
        """Test case for post_employee_access_request_api_v1_corp_accesses_employee_post

        Post Employee Access Request
        """
        pass

    def test_post_oauth_credentials_api_v1_auth_integrations_oauth_provider_post(self) -> None:
        """Test case for post_oauth_credentials_api_v1_auth_integrations_oauth_provider_post

        Post Oauth Credentials
        """
        pass

    def test_refresh_token_api_v1_auth_refresh_token_post(self) -> None:
        """Test case for refresh_token_api_v1_auth_refresh_token_post

        Refresh Token
        """
        pass

    def test_resend_verification_email_api_v1_auth_resend_verification_email_get(self) -> None:
        """Test case for resend_verification_email_api_v1_auth_resend_verification_email_get

        Resend Verification Email
        """
        pass

    def test_reset_password_api_v1_auth_reset_password_post(self) -> None:
        """Test case for reset_password_api_v1_auth_reset_password_post

        Reset Password
        """
        pass

    def test_retrieve_alert_api_v1_metering_alerts_id_get(self) -> None:
        """Test case for retrieve_alert_api_v1_metering_alerts_id_get

        Retrieve Alert
        """
        pass

    def test_retrieve_link_token_api_v1_auth_plaid_get_link_token_get(self) -> None:
        """Test case for retrieve_link_token_api_v1_auth_plaid_get_link_token_get

        Retrieve Link Token
        """
        pass

    def test_retrieve_metered_service_api_v1_metering_services_id_get(self) -> None:
        """Test case for retrieve_metered_service_api_v1_metering_services_id_get

        Retrieve Metered Service
        """
        pass

    def test_sign_in_api_v1_auth_sign_in_post(self) -> None:
        """Test case for sign_in_api_v1_auth_sign_in_post

        Sign In
        """
        pass

    def test_sign_out_api_v1_auth_signout_get(self) -> None:
        """Test case for sign_out_api_v1_auth_signout_get

        Sign Out
        """
        pass

    def test_signin_credentials_api_v1_auth_signin_credentials_post(self) -> None:
        """Test case for signin_credentials_api_v1_auth_signin_credentials_post

        Signin Credentials
        """
        pass

    def test_signout_all_api_v1_auth_signout_all_get(self) -> None:
        """Test case for signout_all_api_v1_auth_signout_all_get

        Signout All
        """
        pass

    def test_update_alert_api_v1_metering_alerts_id_put(self) -> None:
        """Test case for update_alert_api_v1_metering_alerts_id_put

        Update Alert
        """
        pass

    def test_update_api_key_integration_api_v1_auth_integrations_api_key_key_id_put(self) -> None:
        """Test case for update_api_key_integration_api_v1_auth_integrations_api_key_key_id_put

        Update Api Key Integration
        """
        pass

    def test_update_channel_api_v1_notifications_channels_id_put(self) -> None:
        """Test case for update_channel_api_v1_notifications_channels_id_put

        Update Channel
        """
        pass

    def test_update_company_api_v1_auth_company_update_put(self) -> None:
        """Test case for update_company_api_v1_auth_company_update_put

        Update Company
        """
        pass

    def test_update_employee_api_v1_corp_employees_employee_id_put(self) -> None:
        """Test case for update_employee_api_v1_corp_employees_employee_id_put

        Update Employee
        """
        pass

    def test_update_metered_service_api_v1_metering_services_id_put(self) -> None:
        """Test case for update_metered_service_api_v1_metering_services_id_put

        Update Metered Service
        """
        pass

    def test_update_notification_api_v1_notifications_id_put(self) -> None:
        """Test case for update_notification_api_v1_notifications_id_put

        Update Notification
        """
        pass

    def test_update_user_api_v1_auth_me_update_put(self) -> None:
        """Test case for update_user_api_v1_auth_me_update_put

        Update User
        """
        pass

    def test_update_user_license_schema_api_v1_auth_license_update_put(self) -> None:
        """Test case for update_user_license_schema_api_v1_auth_license_update_put

        Update User License Schema
        """
        pass

    def test_upload_company_logo_api_v1_auth_company_logo_post(self) -> None:
        """Test case for upload_company_logo_api_v1_auth_company_logo_post

        Upload Company Logo
        """
        pass

    def test_upload_contract_api_v1_corp_contracts_upload_post(self) -> None:
        """Test case for upload_contract_api_v1_corp_contracts_upload_post

        Upload Contract
        """
        pass

    def test_upload_tool_access_api_v1_corp_accesses_upload_post(self) -> None:
        """Test case for upload_tool_access_api_v1_corp_accesses_upload_post

        Upload Tool Access
        """
        pass

    def test_upsert_contract_api_v1_corp_contracts_contract_id_post(self) -> None:
        """Test case for upsert_contract_api_v1_corp_contracts_contract_id_post

        Upsert Contract
        """
        pass

    def test_upsert_contract_tool_api_v1_corp_contracts_tools_rel_id_post(self) -> None:
        """Test case for upsert_contract_tool_api_v1_corp_contracts_tools_rel_id_post

        Upsert Contract Tool
        """
        pass

    def test_upsert_department_api_v1_corp_departments_dept_id_post(self) -> None:
        """Test case for upsert_department_api_v1_corp_departments_dept_id_post

        Upsert Department
        """
        pass

    def test_upsert_tool_api_v1_tools_tools_tool_id_post(self) -> None:
        """Test case for upsert_tool_api_v1_tools_tools_tool_id_post

        Upsert Tool
        """
        pass


if __name__ == '__main__':
    unittest.main()
