# coding: utf-8

"""
    Anch.io

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Contact: opensource@anchio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from anchio.models.slack_channel_topic import SlackChannelTopic

class TestSlackChannelTopic(unittest.TestCase):
    """SlackChannelTopic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SlackChannelTopic:
        """Test SlackChannelTopic
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SlackChannelTopic`
        """
        model = SlackChannelTopic()
        if include_optional:
            return SlackChannelTopic(
                value = '',
                creator = '',
                last_set = 56
            )
        else:
            return SlackChannelTopic(
                value = '',
                creator = '',
                last_set = 56,
        )
        """

    def testSlackChannelTopic(self):
        """Test SlackChannelTopic"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
