
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-28T08:16:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1d8103cb673c17a32113e1af3ffadeaf7c2f551e",
 "version": "0.7.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
