from contextlib import ContextDecorator
from enot.quantization.fake_quantized_model import FakeQuantizedModel as FakeQuantizedModel

class disable_quantization_mode(ContextDecorator):
    """Context manager which enables and disables fake quantization modules."""
    def __init__(self, model) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, exc_traceback: types.TracebackType | None) -> None: ...
