
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-28T13:17:37+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "eb8c8d60f0625ea4c47d20d3e746b207bafdf1b3",
 "version": "2.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
