# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/acp/v0/cad_component.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ansys.api.acp.v0 import base_pb2 as ansys_dot_api_dot_acp_dot_v0_dot_base__pb2
from ansys.api.acp.v0 import enum_types_pb2 as ansys_dot_api_dot_acp_dot_v0_dot_enum__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$ansys/api/acp/v0/cad_component.proto\x12\x1e\x61nsys.api.acp.v0.cad_component\x1a\x1b\x61nsys/api/acp/v0/base.proto\x1a!ansys/api/acp/v0/enum_types.proto\"S\n\nProperties\x12\x37\n\x06status\x18\x01 \x01(\x0e\x32\'.ansys.api.acp.v0.enum_types.StatusType\x12\x0c\n\x04path\x18\x02 \x01(\t\"|\n\nObjectInfo\x12.\n\x04info\x18\x01 \x01(\x0b\x32 .ansys.api.acp.v0.base.BasicInfo\x12>\n\nproperties\x18\x02 \x01(\x0b\x32*.ansys.api.acp.v0.cad_component.Properties\"H\n\tListReply\x12;\n\x07objects\x18\x01 \x03(\x0b\x32*.ansys.api.acp.v0.cad_component.ObjectInfo\"L\n\x0eRefreshRequest\x12:\n\rresource_path\x18\x01 \x01(\x0b\x32#.ansys.api.acp.v0.base.ResourcePath2\xbc\x01\n\rObjectService\x12U\n\x04List\x12\".ansys.api.acp.v0.base.ListRequest\x1a).ansys.api.acp.v0.cad_component.ListReply\x12T\n\x03Get\x12!.ansys.api.acp.v0.base.GetRequest\x1a*.ansys.api.acp.v0.cad_component.ObjectInfob\x06proto3')



_PROPERTIES = DESCRIPTOR.message_types_by_name['Properties']
_OBJECTINFO = DESCRIPTOR.message_types_by_name['ObjectInfo']
_LISTREPLY = DESCRIPTOR.message_types_by_name['ListReply']
_REFRESHREQUEST = DESCRIPTOR.message_types_by_name['RefreshRequest']
Properties = _reflection.GeneratedProtocolMessageType('Properties', (_message.Message,), {
  'DESCRIPTOR' : _PROPERTIES,
  '__module__' : 'ansys.api.acp.v0.cad_component_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.acp.v0.cad_component.Properties)
  })
_sym_db.RegisterMessage(Properties)

ObjectInfo = _reflection.GeneratedProtocolMessageType('ObjectInfo', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTINFO,
  '__module__' : 'ansys.api.acp.v0.cad_component_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.acp.v0.cad_component.ObjectInfo)
  })
_sym_db.RegisterMessage(ObjectInfo)

ListReply = _reflection.GeneratedProtocolMessageType('ListReply', (_message.Message,), {
  'DESCRIPTOR' : _LISTREPLY,
  '__module__' : 'ansys.api.acp.v0.cad_component_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.acp.v0.cad_component.ListReply)
  })
_sym_db.RegisterMessage(ListReply)

RefreshRequest = _reflection.GeneratedProtocolMessageType('RefreshRequest', (_message.Message,), {
  'DESCRIPTOR' : _REFRESHREQUEST,
  '__module__' : 'ansys.api.acp.v0.cad_component_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.acp.v0.cad_component.RefreshRequest)
  })
_sym_db.RegisterMessage(RefreshRequest)

_OBJECTSERVICE = DESCRIPTOR.services_by_name['ObjectService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROPERTIES._serialized_start=136
  _PROPERTIES._serialized_end=219
  _OBJECTINFO._serialized_start=221
  _OBJECTINFO._serialized_end=345
  _LISTREPLY._serialized_start=347
  _LISTREPLY._serialized_end=419
  _REFRESHREQUEST._serialized_start=421
  _REFRESHREQUEST._serialized_end=497
  _OBJECTSERVICE._serialized_start=500
  _OBJECTSERVICE._serialized_end=688
# @@protoc_insertion_point(module_scope)
