# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: codefly/actions/v0/module.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'codefly/actions/v0/module.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63odefly/actions/v0/module.proto\x12\x12\x63odefly.actions.v0\x1a\x1b\x62uf/validate/validate.proto\"`\n\tNewModule\x12\x12\n\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1d\n\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18\x32R\x04name\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scriptionB\xcc\x01\n\x16\x63om.codefly.actions.v0B\x0bModuleProtoP\x01Z;github.com/codefly-dev/core/generated/go/codefly/actions/v0\xa2\x02\x03\x43\x41V\xaa\x02\x12\x43odefly.Actions.V0\xca\x02\x12\x43odefly\\Actions\\V0\xe2\x02\x1e\x43odefly\\Actions\\V0\\GPBMetadata\xea\x02\x14\x43odefly::Actions::V0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'codefly.actions.v0.module_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.codefly.actions.v0B\013ModuleProtoP\001Z;github.com/codefly-dev/core/generated/go/codefly/actions/v0\242\002\003CAV\252\002\022Codefly.Actions.V0\312\002\022Codefly\\Actions\\V0\342\002\036Codefly\\Actions\\V0\\GPBMetadata\352\002\024Codefly::Actions::V0'
  _globals['_NEWMODULE'].fields_by_name['name']._loaded_options = None
  _globals['_NEWMODULE'].fields_by_name['name']._serialized_options = b'\272H\006r\004\020\003\0302'
  _globals['_NEWMODULE']._serialized_start=84
  _globals['_NEWMODULE']._serialized_end=180
# @@protoc_insertion_point(module_scope)
