
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-29T19:05:41-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8fe25bda2f0d731ce5b52f55df0be80bf650514b",
 "version": "0.9.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
