# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `rime-api-key` header.

    The version of the OpenAPI document: 1.0
    Contact: dev@robustintelligence.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from ri.apiclient.models.user_update_user_request import UserUpdateUserRequest

class TestUserUpdateUserRequest(unittest.TestCase):
    """UserUpdateUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserUpdateUserRequest:
        """Test UserUpdateUserRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserUpdateUserRequest`
        """
        model = UserUpdateUserRequest()
        if include_optional:
            return UserUpdateUserRequest(
                user = ri.apiclient.models.user_update_user_request_user.User_UpdateUser_request_user(
                    id = ri.apiclient.models.id.id(), 
                    name = '', 
                    role = 'ROLE_UNSPECIFIED', 
                    email = '', 
                    full_name = '', 
                    show_tutorial = True, 
                    org_role = 'ACTOR_ROLE_UNSPECIFIED', 
                    private_info = ri.apiclient.models.user_private_info.userPrivateInfo(
                        favorite_projects = [
                            ri.apiclient.models.user_favorite_projects.userFavoriteProjects(
                                workspace_id = ri.apiclient.models.rime_uuid.rimeUUID(
                                    uuid = '', ), 
                                project_ids = [
                                    ri.apiclient.models.rime_uuid.rimeUUID(
                                        uuid = '', )
                                    ], )
                            ], ), ),
                mask = ri.apiclient.models.rime_user_write_mask.rimeUserWriteMask(
                    full_name = True, 
                    show_tutorial = True, 
                    role = True, 
                    org_role = True, 
                    private_info = True, )
            )
        else:
            return UserUpdateUserRequest(
        )
        """

    def testUserUpdateUserRequest(self):
        """Test UserUpdateUserRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()