# Generated by Django 5.0.3 on 2024-04-03 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_chatsession_verification_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='verified_by',
            field=models.ManyToManyField(blank=True, related_name='verified_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
