# Generated by Django 5.0.3 on 2024-04-04 07:01
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_chatsession_verified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='additional_comments',
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,  # Remove the default value for created_at
        ),
        migrations.AddField(
            model_name='feedback',
            name='session_id',
            field=models.CharField(max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.BooleanField(),
        ),
    ]
