# Generated by Django 5.0.3 on 2024-04-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_alter_uploadedfile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='similarquestion',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
