from python.libdaw.time import Duration, Timestamp


class Tone:
    def __new__(cls: type, start: Timestamp, length: Duration, frequency: float): ...
    @property
    def start(self) -> Timestamp: ...
    @property
    def length(self) -> Duration: ...
    @property
    def frequency(self) -> float: ...
