# Generated by Django 5.0.6 on 2024-06-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_parameter_inputtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='max_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='min_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
