from libdaw import Node

class Sawtooth(Node):
    def __new__(cls: type, sample_rate: int = 48000, frequency: float = 0.0): ...
    @property
    def frequency(self) -> float: ...
    @frequency.setter
    def frequency(self, value: float): ...

class Sine(Node):
    def __new__(cls: type, sample_rate: int = 48000, frequency: float = 0.0): ...
    @property
    def frequency(self) -> float: ...
    @frequency.setter
    def frequency(self, value: float): ...

class Square(Node):
    def __new__(cls: type, sample_rate: int = 48000, frequency: float = 0.0): ...
    @property
    def frequency(self) -> float: ...
    @frequency.setter
    def frequency(self, value: float): ...

class Triangle(Node):
    def __new__(cls: type, sample_rate: int = 48000, frequency: float = 0.0): ...
    @property
    def frequency(self) -> float: ...
    @frequency.setter
    def frequency(self, value: float): ...

