# Copyright 3000 Test Tester. All rights reserved.
#
# This file was generated by BlueCat Automation Toolkit (BATK).
# Portions which reproduce template contents from BATK are Copyright 2023 BlueCat Networks Inc.
# Other contents are owned by their authors.
"""Event handlers of workflow `tester_workflow`."""


def initialize():
    """Handle the `initialize` event."""
    # Load the modules that add routes to the blueprint instance.
    # NOTE: Some tools may report the import statement as unnecessary/unused.
    # pylint: disable=unused-import
    from . import routes  # noqa: F401


def attach(application):
    """Attach request handlers to the web application."""
    from .base import bp

    application.register_blueprint(bp)
