# Generated by Django 5.0.3 on 2024-04-02 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_user_id_chatsession_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
