# Generated by Django 5.0.3 on 2024-04-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_chatsession_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user_session_id',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_identifier',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(max_length=32),
        ),
    ]

