# Generated by Django 5.0.3 on 2024-04-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_remove_feedback_additional_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('session_id', models.CharField(max_length=50)),
                ('user_session_id', models.CharField(max_length=50)),
            ],
        ),
    ]
