"""Constant paths to files and directories in the user repository."""


FILE_METADATA = ".github/.metadata.json"
FILE_LICENSE = "LICENSE"
FILE_README_MAIN = "README.md"
FILE_FUNDING = ".github/FUNDING.yml"
FILE_PRE_COMMIT_CONFIG_MAIN = ".github/.pre-commit-config-main.yaml"
FILE_PRE_COMMIT_CONFIG_RELEASE = ".github/.pre-commit-config-release.yaml"
FILE_PRE_COMMIT_CONFIG_PRE_RELEASE = ".github/.pre-commit-config-pre-release.yaml"
FILE_PRE_COMMIT_CONFIG_IMPLEMENTATION = ".github/.pre-commit-config-implementation.yaml"
FILE_PRE_COMMIT_CONFIG_DEVELOPMENT = ".github/.pre-commit-config-development.yaml"
FILE_PRE_COMMIT_CONFIG_AUTO_UPDATE = ".github/.pre-commit-config-auto-update.yaml"
FILE_PRE_COMMIT_CONFIG_OTHER = ".github/.pre-commit-config-other.yaml"
FILE_READTHEDOCS_CONFIG = ".github/.readthedocs.yaml"
FILE_ISSUE_TEMPLATE_CHOOSER_CONFIG = ".github/ISSUE_TEMPLATE/config.yml"
FILE_PYTHON_PYPROJECT = "pyproject.toml"
FILE_PYTHON_REQUIREMENTS = "requirements.txt"
FILE_PYTHON_MANIFEST = "MANIFEST.in"
FILE_CODECOV_CONFIG = ".github/.codecov.yml"
FILE_GITIGNORE = ".gitignore"
FILE_GITATTRIBUTES = ".gitattributes"
FILE_PATH_META = ".github/.control_center_path.txt"
DIR_GITHUB = ".github/"
DIR_GITHUB_WORKFLOWS = ".github/workflows/"
DIR_GITHUB_WORKFLOW_REQUIREMENTS = ".github/workflow_requirements/"
DIR_GITHUB_ISSUE_TEMPLATE = ".github/ISSUE_TEMPLATE/"
DIR_GITHUB_PULL_REQUEST_TEMPLATE = ".github/PULL_REQUEST_TEMPLATE/"
DIR_GITHUB_DISCUSSION_TEMPLATE = ".github/DISCUSSION_TEMPLATE/"
