# coding: utf-8

"""
    Anch.io

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.9
    Contact: opensource@anchio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictInt, StrictStr
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class BankAccountSchema(BaseModel):
    """
    BankAccountSchema
    """ # noqa: E501
    created_on: Optional[StrictStr] = None
    updated_on: Optional[StrictStr] = None
    id: StrictStr
    provider: StrictStr
    name: StrictStr
    account_id: StrictStr
    type: StrictStr
    subtype: StrictStr
    connected_tools: Optional[StrictInt] = 0
    last_sync_date: Optional[StrictStr] = None
    institution: StrictStr
    logo: Optional[StrictStr] = None
    oauth_token: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["created_on", "updated_on", "id", "provider", "name", "account_id", "type", "subtype", "connected_tools", "last_sync_date", "institution", "logo", "oauth_token"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BankAccountSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if created_on (nullable) is None
        # and model_fields_set contains the field
        if self.created_on is None and "created_on" in self.model_fields_set:
            _dict['created_on'] = None

        # set to None if updated_on (nullable) is None
        # and model_fields_set contains the field
        if self.updated_on is None and "updated_on" in self.model_fields_set:
            _dict['updated_on'] = None

        # set to None if last_sync_date (nullable) is None
        # and model_fields_set contains the field
        if self.last_sync_date is None and "last_sync_date" in self.model_fields_set:
            _dict['last_sync_date'] = None

        # set to None if logo (nullable) is None
        # and model_fields_set contains the field
        if self.logo is None and "logo" in self.model_fields_set:
            _dict['logo'] = None

        # set to None if oauth_token (nullable) is None
        # and model_fields_set contains the field
        if self.oauth_token is None and "oauth_token" in self.model_fields_set:
            _dict['oauth_token'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of BankAccountSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_on": obj.get("created_on"),
            "updated_on": obj.get("updated_on"),
            "id": obj.get("id"),
            "provider": obj.get("provider"),
            "name": obj.get("name"),
            "account_id": obj.get("account_id"),
            "type": obj.get("type"),
            "subtype": obj.get("subtype"),
            "connected_tools": obj.get("connected_tools") if obj.get("connected_tools") is not None else 0,
            "last_sync_date": obj.get("last_sync_date"),
            "institution": obj.get("institution"),
            "logo": obj.get("logo"),
            "oauth_token": obj.get("oauth_token")
        })
        return _obj


