# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ai_api.models.job_instance_in import JobInstanceIn

class TestJobInstanceIn(unittest.TestCase):
    """JobInstanceIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobInstanceIn:
        """Test JobInstanceIn
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobInstanceIn`
        """
        model = JobInstanceIn()
        if include_optional:
            return JobInstanceIn(
                name = '',
                job_name = '',
                repository_url = '',
                starting_commit = '',
                cluster = '',
                userlogin = ''
            )
        else:
            return JobInstanceIn(
                name = '',
                job_name = '',
                repository_url = '',
                starting_commit = '',
                cluster = '',
                userlogin = '',
        )
        """

    def testJobInstanceIn(self):
        """Test JobInstanceIn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
