
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-01T10:04:10-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c62b1f10cb72bcd2e6517ce4dd0bf3f15310d9de",
 "version": "2.39.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
