// automatically generated by the FlatBuffers compiler, do not modify

package jp.oist.abcvlib.core.learning.fbclasses;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RobotAction extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static RobotAction getRootAsRobotAction(ByteBuffer _bb) { return getRootAsRobotAction(_bb, new RobotAction()); }
  public static RobotAction getRootAsRobotAction(ByteBuffer _bb, RobotAction obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RobotAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public jp.oist.abcvlib.core.learning.fbclasses.MotionAction motionAction() { return motionAction(new jp.oist.abcvlib.core.learning.fbclasses.MotionAction()); }
  public jp.oist.abcvlib.core.learning.fbclasses.MotionAction motionAction(jp.oist.abcvlib.core.learning.fbclasses.MotionAction obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public jp.oist.abcvlib.core.learning.fbclasses.CommAction commAction() { return commAction(new jp.oist.abcvlib.core.learning.fbclasses.CommAction()); }
  public jp.oist.abcvlib.core.learning.fbclasses.CommAction commAction(jp.oist.abcvlib.core.learning.fbclasses.CommAction obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createRobotAction(FlatBufferBuilder builder,
      int motion_actionOffset,
      int comm_actionOffset) {
    builder.startTable(2);
    RobotAction.addCommAction(builder, comm_actionOffset);
    RobotAction.addMotionAction(builder, motion_actionOffset);
    return RobotAction.endRobotAction(builder);
  }

  public static void startRobotAction(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addMotionAction(FlatBufferBuilder builder, int motionActionOffset) { builder.addOffset(0, motionActionOffset, 0); }
  public static void addCommAction(FlatBufferBuilder builder, int commActionOffset) { builder.addOffset(1, commActionOffset, 0); }
  public static int endRobotAction(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RobotAction get(int j) { return get(new RobotAction(), j); }
    public RobotAction get(RobotAction obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

