# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ReflectionPropertyType(str, Enum):
    """
    Definition type of the reflection properties of the space object
    """

    """
    allowed enum values
    """
    ISOTROPIC_SINGLE_COEFFICIENT = 'ISOTROPIC_SINGLE_COEFFICIENT'
    ISOTROPIC_CA_CR = 'ISOTROPIC_CA_CR'
    SOLAR_ARRAY = 'SOLAR_ARRAY'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ReflectionPropertyType from a JSON string"""
        return cls(json.loads(json_str))


