# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: base/v0/spec.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'base/v0/spec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62\x61se/v0/spec.proto\x12\x07\x62\x61se.v0\x1a\x19google/protobuf/any.proto\"$\n\x0cGenericValue\x12\x14\n\x05value\x18\x01 \x01(\x0cR\x05value\"7\n\tSpecValue\x12*\n\x05value\x18\x01 \x01(\x0b\x32\x14.google.protobuf.AnyR\x05value\"\x8a\x01\n\x05Specs\x12\x32\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x1a.base.v0.Specs.FieldsEntryR\x06\x66ields\x1aM\n\x0b\x46ieldsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x12.base.v0.SpecValueR\x05value:\x02\x38\x01\x42\x87\x01\n\x0b\x63om.base.v0B\tSpecProtoP\x01Z0github.com/codefly-dev/core/generated/go/base/v0\xa2\x02\x03\x42VX\xaa\x02\x07\x42\x61se.V0\xca\x02\x07\x42\x61se\\V0\xe2\x02\x13\x42\x61se\\V0\\GPBMetadata\xea\x02\x08\x42\x61se::V0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base.v0.spec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.base.v0B\tSpecProtoP\001Z0github.com/codefly-dev/core/generated/go/base/v0\242\002\003BVX\252\002\007Base.V0\312\002\007Base\\V0\342\002\023Base\\V0\\GPBMetadata\352\002\010Base::V0'
  _globals['_SPECS_FIELDSENTRY']._loaded_options = None
  _globals['_SPECS_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_GENERICVALUE']._serialized_start=58
  _globals['_GENERICVALUE']._serialized_end=94
  _globals['_SPECVALUE']._serialized_start=96
  _globals['_SPECVALUE']._serialized_end=151
  _globals['_SPECS']._serialized_start=154
  _globals['_SPECS']._serialized_end=292
  _globals['_SPECS_FIELDSENTRY']._serialized_start=215
  _globals['_SPECS_FIELDSENTRY']._serialized_end=292
# @@protoc_insertion_point(module_scope)
