def help():
    print("""Avalable Commands:
1- YWP.install_packages
2- YWP.install_libraries
3- YWP.upgrade_libraries
4- YWP.upgrade_library
5- YWP
6- YWP.help
7- YWP.Audios.play_sound
8- YWP.Audios.play_audio
9- YWP.Audios.record_audio
10- YWP.Audios.transcribe_audio_offline
11- YWP.Audios.transcribe_audio
12- YWP.Audios.text_to_speech
13- YWP.Audios.text_to_speech_offline
14- YWP.Audios.play_audio_online
15- YWP.Files.create_file
16- YWP.Files.open_file
17- YWP.Files.delete_all_files
18- YWP.Websites.open_website
19- YWP.Crypto.token_information
20- YWP.VideosCreator.Basic.basic_video_creator
21- YWP.endecrypt.aes.encrypt
22- YWP.endecrypt.aes.decrypt
23- YWP.endecrypt.BlowFish.encrypt
24- YWP.endecrypt.BlowFish.decrypt
25- YWP.endecrypt.Base64.encrypt
26- YWP.endecrypt.Base64.decrypt
27- YWP.endecrypt.Hex.encrypt
28- YWP.endecrypt.Hex.decrypt
29- YWP.Libraries.Basic.init_creator
30- YWP.Libraries.Basic.basic_setup_file_creator
31- YWP.Libraries.Basic.upload_file_creator
32- YWP.Files.delete_file""")