# -*- coding: utf-8 -*-

"""
form3publicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MethodEnum(object):

    """Implementation of the 'Method' enum.

    Method used to settle the payment instruction. Acceptable Values for SEPA:
    CLRG. Acceptable Values for SWIFT: INDA (settled by Instructed Agent),
    INGA (Settled by Instructing Agent), COVE (Cover Payment)

    Attributes:
        CLRG: TODO: type description here.
        COVE: TODO: type description here.
        INGA: TODO: type description here.
        INDA: TODO: type description here.

    """
    CLRG = 'CLRG'

    COVE = 'COVE'

    INGA = 'INGA'

    INDA = 'INDA'

