# -*- coding: utf-8 -*-

"""
form3publicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class NameVerificationAdmissionReasonCodeEnum(object):

    """Implementation of the 'NameVerificationAdmissionReasonCode' enum.

    TODO: type enum description here.

    Attributes:
        ANNM: TODO: type description here.
        MBAM: TODO: type description here.
        BANM: TODO: type description here.
        PANM: TODO: type description here.
        BAMM: TODO: type description here.
        PAMM: TODO: type description here.
        AC01: TODO: type description here.
        IVCR: TODO: type description here.
        CASS: TODO: type description here.
        SCNS: TODO: type description here.
        ACNS: TODO: type description here.
        OPTO: TODO: type description here.

    """
    ANNM = 'ANNM'

    MBAM = 'MBAM'

    BANM = 'BANM'

    PANM = 'PANM'

    BAMM = 'BAMM'

    PAMM = 'PAMM'

    AC01 = 'AC01'

    IVCR = 'IVCR'

    CASS = 'CASS'

    SCNS = 'SCNS'

    ACNS = 'ACNS'

    OPTO = 'OPTO'

