# -*- coding: utf-8 -*-

"""
form3publicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PaymentAdmissionResourceTypeEnum(object):

    """Implementation of the 'PaymentAdmissionResourceType' enum.

    TODO: type enum description here.

    Attributes:
        PAYMENT_ADMISSIONS: TODO: type description here.

    """
    PAYMENT_ADMISSIONS = 'payment_admissions'

