# -*- coding: utf-8 -*-

"""
form3publicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PaymentRecallResourceTypeEnum(object):

    """Implementation of the 'PaymentRecallResourceType' enum.

    TODO: type enum description here.

    Attributes:
        RECALLS: TODO: type description here.

    """
    RECALLS = 'recalls'

