# -*- coding: utf-8 -*-

"""
form3publicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from form3publicapi.api_helper import APIHelper
from form3publicapi.models.report_1 import Report1
from form3publicapi.models.report_request_submission_2 import ReportRequestSubmission2


class ReportRequestRelationships(object):

    """Implementation of the 'ReportRequestRelationships' model.

    TODO: type model description here.

    Attributes:
        report (Report1): TODO: type description here.
        report_request_submission (ReportRequestSubmission2): TODO: type
            description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "report": 'report',
        "report_request_submission": 'report_request_submission'
    }

    _optionals = [
        'report',
        'report_request_submission',
    ]

    def __init__(self,
                 report=APIHelper.SKIP,
                 report_request_submission=APIHelper.SKIP):
        """Constructor for the ReportRequestRelationships class"""

        # Initialize members of the class
        if report is not APIHelper.SKIP:
            self.report = report 
        if report_request_submission is not APIHelper.SKIP:
            self.report_request_submission = report_request_submission 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        report = Report1.from_dictionary(dictionary.get('report')) if 'report' in dictionary.keys() else APIHelper.SKIP
        report_request_submission = ReportRequestSubmission2.from_dictionary(dictionary.get('report_request_submission')) if 'report_request_submission' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(report,
                   report_request_submission)
