# -*- coding: utf-8 -*-

"""
form3publicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type6Enum(object):

    """Implementation of the 'Type6' enum.

    TODO: type enum description here.

    Attributes:
        MISSING: TODO: type description here.
        INCORRECT: TODO: type description here.

    """
    MISSING = 'missing'

    INCORRECT = 'incorrect'

