
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-28T23:42:04+0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "df8e0cb2278ad6c78e1e2b983642dc92d2d6dae5",
 "version": "4.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
