
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-03T14:50:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "df769f6c75d8598de4be08f8053831e39263d96b",
 "version": "2.24.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
