
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-02T16:13:21+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "20bd2dfe3fff29ff116455216ca368c13b4b6ad0",
 "version": "1.8.36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
