# -*- coding: utf-8 -*-

"""
form3publicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DirectDebitResourceTypeEnum(object):

    """Implementation of the 'DirectDebitResourceType' enum.

    TODO: type enum description here.

    Attributes:
        DIRECT_DEBITS: TODO: type description here.
        DIRECT_DEBIT_STATUS: TODO: type description here.
        DIRECT_DEBIT_ADMISSIONS: TODO: type description here.
        DIRECT_DEBIT_SUBMISSIONS: TODO: type description here.
        DIRECT_DEBIT_SUBMISSION_VALIDATIONS: TODO: type description here.
        DIRECT_DEBIT_REVERSALS: TODO: type description here.
        DIRECT_DEBIT_REVERSAL_ADMISSIONS: TODO: type description here.
        DIRECT_DEBIT_REVERSAL_SUBMISSIONS: TODO: type description here.
        DIRECT_DEBIT_REVERSAL_SUBMISSION_VALIDATIONS: TODO: type description
            here.
        DIRECT_DEBIT_RETURNS: TODO: type description here.
        DIRECT_DEBIT_RETURN_ADMISSIONS: TODO: type description here.
        DIRECT_DEBIT_RETURN_SUBMISSIONS: TODO: type description here.
        DIRECT_DEBIT_RETURN_SUBMISSION_VALIDATIONS: TODO: type description
            here.
        DIRECT_DEBIT_RETURN_REVERSALS: TODO: type description here.
        DIRECT_DEBIT_RETURN_REVERSAL_ADMISSIONS: TODO: type description here.
        DIRECT_DEBIT_AUTOMATIC_RETURNS: TODO: type description here.
        DIRECT_DEBIT_RECALLS: TODO: type description here.
        DIRECT_DEBIT_RECALL_ADMISSIONS: TODO: type description here.
        DIRECT_DEBIT_RECALL_SUBMISSIONS: TODO: type description here.
        DIRECT_DEBIT_RECALL_SUBMISSION_VALIDATIONS: TODO: type description
            here.
        DIRECT_DEBIT_DECISIONS: TODO: type description here.
        DIRECT_DEBIT_DECISION_ADMISSIONS: TODO: type description here.
        DIRECT_DEBIT_DECISION_SUBMISSIONS: TODO: type description here.
        DIRECT_DEBIT_DECISION_SUBMISSION_VALIDATIONS: TODO: type description
            here.
        DIRECT_DEBIT_SUBMISSIONS_WITH_FINAL_STATE: TODO: type description
            here.
        DIRECT_DEBIT_RETURN_SUBMISSIONS_WITH_FINAL_STATE: TODO: type
            description here.

    """
    DIRECT_DEBITS = 'direct_debits'

    DIRECT_DEBIT_STATUS = 'direct_debit_status'

    DIRECT_DEBIT_ADMISSIONS = 'direct_debit_admissions'

    DIRECT_DEBIT_SUBMISSIONS = 'direct_debit_submissions'

    DIRECT_DEBIT_SUBMISSION_VALIDATIONS = 'direct_debit_submission_validations'

    DIRECT_DEBIT_REVERSALS = 'direct_debit_reversals'

    DIRECT_DEBIT_REVERSAL_ADMISSIONS = 'direct_debit_reversal_admissions'

    DIRECT_DEBIT_REVERSAL_SUBMISSIONS = 'direct_debit_reversal_submissions'

    DIRECT_DEBIT_REVERSAL_SUBMISSION_VALIDATIONS = 'direct_debit_reversal_submission_validations'

    DIRECT_DEBIT_RETURNS = 'direct_debit_returns'

    DIRECT_DEBIT_RETURN_ADMISSIONS = 'direct_debit_return_admissions'

    DIRECT_DEBIT_RETURN_SUBMISSIONS = 'direct_debit_return_submissions'

    DIRECT_DEBIT_RETURN_SUBMISSION_VALIDATIONS = 'direct_debit_return_submission_validations'

    DIRECT_DEBIT_RETURN_REVERSALS = 'direct_debit_return_reversals'

    DIRECT_DEBIT_RETURN_REVERSAL_ADMISSIONS = 'direct_debit_return_reversal_admissions'

    DIRECT_DEBIT_AUTOMATIC_RETURNS = 'direct_debit_automatic_returns'

    DIRECT_DEBIT_RECALLS = 'direct_debit_recalls'

    DIRECT_DEBIT_RECALL_ADMISSIONS = 'direct_debit_recall_admissions'

    DIRECT_DEBIT_RECALL_SUBMISSIONS = 'direct_debit_recall_submissions'

    DIRECT_DEBIT_RECALL_SUBMISSION_VALIDATIONS = 'direct_debit_recall_submission_validations'

    DIRECT_DEBIT_DECISIONS = 'direct_debit_decisions'

    DIRECT_DEBIT_DECISION_ADMISSIONS = 'direct_debit_decision_admissions'

    DIRECT_DEBIT_DECISION_SUBMISSIONS = 'direct_debit_decision_submissions'

    DIRECT_DEBIT_DECISION_SUBMISSION_VALIDATIONS = 'direct_debit_decision_submission_validations'

    DIRECT_DEBIT_SUBMISSIONS_WITH_FINAL_STATE = 'direct_debit_submissions_with_final_state'

    DIRECT_DEBIT_RETURN_SUBMISSIONS_WITH_FINAL_STATE = 'direct_debit_return_submissions_with_final_state'

