# -*- coding: utf-8 -*-

"""
form3publicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from form3publicapi.api_helper import APIHelper
from form3publicapi.models.direct_debit_1 import DirectDebit1


class DirectDebitSubmissionRelationships(object):

    """Implementation of the 'DirectDebitSubmissionRelationships' model.

    TODO: type model description here.

    Attributes:
        direct_debit (DirectDebit1): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "direct_debit": 'direct_debit'
    }

    _optionals = [
        'direct_debit',
    ]

    def __init__(self,
                 direct_debit=APIHelper.SKIP):
        """Constructor for the DirectDebitSubmissionRelationships class"""

        # Initialize members of the class
        if direct_debit is not APIHelper.SKIP:
            self.direct_debit = direct_debit 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        direct_debit = DirectDebit1.from_dictionary(dictionary.get('direct_debit')) if 'direct_debit' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(direct_debit)
