# -*- coding: utf-8 -*-

"""
form3publicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from form3publicapi.api_helper import APIHelper


class QueryResponseSubmissionAttributes(object):

    """Implementation of the 'QueryResponseSubmissionAttributes' model.

    TODO: type model description here.

    Attributes:
        auto (bool): TODO: type description here.
        status (QueryResponseSubmissionStatusEnum): TODO: type description
            here.
        status_reason (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "auto": 'auto',
        "status": 'status',
        "status_reason": 'status_reason'
    }

    _optionals = [
        'auto',
        'status',
        'status_reason',
    ]

    def __init__(self,
                 auto=APIHelper.SKIP,
                 status=APIHelper.SKIP,
                 status_reason=APIHelper.SKIP):
        """Constructor for the QueryResponseSubmissionAttributes class"""

        # Initialize members of the class
        if auto is not APIHelper.SKIP:
            self.auto = auto 
        if status is not APIHelper.SKIP:
            self.status = status 
        if status_reason is not APIHelper.SKIP:
            self.status_reason = status_reason 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        auto = dictionary.get("auto") if "auto" in dictionary.keys() else APIHelper.SKIP
        status = dictionary.get("status") if dictionary.get("status") else APIHelper.SKIP
        status_reason = dictionary.get("status_reason") if dictionary.get("status_reason") else APIHelper.SKIP
        # Return an object of this model
        return cls(auto,
                   status,
                   status_reason)
