# -*- coding: utf-8 -*-

"""
form3publicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ReportRequestUserIdCodeEnum(object):

    """Implementation of the 'ReportRequestUserIdCode' enum.

    TODO: type enum description here.

    Attributes:
        SWBIC: TODO: type description here.
        RTN: TODO: type description here.
        PARTICIPANT: TODO: type description here.
        SUN: TODO: type description here.

    """
    SWBIC = 'SWBIC'

    RTN = 'RTN'

    PARTICIPANT = 'Participant'

    SUN = 'SUN'

