# -*- coding: utf-8 -*-

"""
form3publicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class RequestForInformationReference(object):

    """Implementation of the 'RequestForInformationReference' model.

    TODO: type model description here.

    Attributes:
        mtype (str): TODO: type description here.
        value (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": 'type',
        "value": 'value'
    }

    def __init__(self,
                 mtype=None,
                 value=None):
        """Constructor for the RequestForInformationReference class"""

        # Initialize members of the class
        self.mtype = mtype 
        self.value = value 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype = dictionary.get("type") if dictionary.get("type") else None
        value = dictionary.get("value") if dictionary.get("value") else None
        # Return an object of this model
        return cls(mtype,
                   value)
