# -*- coding: utf-8 -*-

"""
form3publicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class RouteEnum(object):

    """Implementation of the 'Route' enum.

    Route taken for an outbound payment

    Attributes:
        ON_US: TODO: type description here.

    """
    ON_US = 'on_us'

