# Generated by Django 4.2.3 on 2024-07-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0018_alter_foodproduct_available_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietordersurvey',
            name='tt',
            field=models.IntegerField(default=0),
        ),
    ]
