
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-01T13:26:20-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "7c55e4712b706128366a12fc3bea82d182b9f1a6",
 "version": "2.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
