# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: codefly/base/v0/network.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'codefly/base/v0/network.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from codefly.base.v0 import scope_pb2 as codefly_dot_base_dot_v0_dot_scope__pb2
from codefly.base.v0 import endpoint_pb2 as codefly_dot_base_dot_v0_dot_endpoint__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63odefly/base/v0/network.proto\x12\x0f\x63odefly.base.v0\x1a\x1b\x63odefly/base/v0/scope.proto\x1a\x1e\x63odefly/base/v0/endpoint.proto\"\x87\x01\n\x0eNetworkMapping\x12\x35\n\x08\x65ndpoint\x18\x01 \x01(\x0b\x32\x19.codefly.base.v0.EndpointR\x08\x65ndpoint\x12>\n\tinstances\x18\x02 \x03(\x0b\x32 .codefly.base.v0.NetworkInstanceR\tinstances\"\xa9\x01\n\x03\x44NS\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n\x06module\x18\x02 \x01(\tR\x06module\x12\x18\n\x07service\x18\x03 \x01(\tR\x07service\x12\x1a\n\x08\x65ndpoint\x18\x04 \x01(\tR\x08\x65ndpoint\x12\x12\n\x04host\x18\x05 \x01(\tR\x04host\x12\x12\n\x04port\x18\x06 \x01(\rR\x04port\x12\x18\n\x07secured\x18\x07 \x01(\x08R\x07secured\"\xa7\x01\n\x0fNetworkInstance\x12\x36\n\x06\x61\x63\x63\x65ss\x18\x01 \x01(\x0b\x32\x1e.codefly.base.v0.NetworkAccessR\x06\x61\x63\x63\x65ss\x12\x12\n\x04host\x18\x03 \x01(\tR\x04host\x12\x1a\n\x08hostname\x18\x04 \x01(\tR\x08hostname\x12\x12\n\x04port\x18\x05 \x01(\rR\x04port\x12\x18\n\x07\x61\x64\x64ress\x18\x06 \x01(\tR\x07\x61\x64\x64ressB\xbb\x01\n\x13\x63om.codefly.base.v0B\x0cNetworkProtoP\x01Z8github.com/codefly-dev/core/generated/go/codefly/base/v0\xa2\x02\x03\x43\x42V\xaa\x02\x0f\x43odefly.Base.V0\xca\x02\x0f\x43odefly\\Base\\V0\xe2\x02\x1b\x43odefly\\Base\\V0\\GPBMetadata\xea\x02\x11\x43odefly::Base::V0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'codefly.base.v0.network_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.codefly.base.v0B\014NetworkProtoP\001Z8github.com/codefly-dev/core/generated/go/codefly/base/v0\242\002\003CBV\252\002\017Codefly.Base.V0\312\002\017Codefly\\Base\\V0\342\002\033Codefly\\Base\\V0\\GPBMetadata\352\002\021Codefly::Base::V0'
  _globals['_NETWORKMAPPING']._serialized_start=112
  _globals['_NETWORKMAPPING']._serialized_end=247
  _globals['_DNS']._serialized_start=250
  _globals['_DNS']._serialized_end=419
  _globals['_NETWORKINSTANCE']._serialized_start=422
  _globals['_NETWORKINSTANCE']._serialized_end=589
# @@protoc_insertion_point(module_scope)
