# Generated by Django 4.2 on 2023-09-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_blog_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='blog/images/'),
        ),
    ]
