
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-28T13:19:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "51a7ff1afb722cff5dc8b3122d50b0bb6ef06cc8",
 "version": "1.0.91"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
