# coding: utf-8

"""
    AIForged API

    Integration with AI Forged system  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: support@aiforged.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_ai_forged_view_models_verification_summary_doc_status import OneOfAIForgedViewModelsVerificationSummaryDocStatus  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfAIForgedViewModelsVerificationSummaryDocStatus(unittest.TestCase):
    """OneOfAIForgedViewModelsVerificationSummaryDocStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfAIForgedViewModelsVerificationSummaryDocStatus(self):
        """Test OneOfAIForgedViewModelsVerificationSummaryDocStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_ai_forged_view_models_verification_summary_doc_status.OneOfAIForgedViewModelsVerificationSummaryDocStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
