# coding: utf-8

"""
    AIForged API

    Integration with AI Forged system  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: support@aiforged.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.method4 import Method4  # noqa: E501
from swagger_client.rest import ApiException


class TestMethod4(unittest.TestCase):
    """Method4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMethod4(self):
        """Test Method4"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.method4.Method4()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
