# Generated by Django 5.0.3 on 2024-04-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_similarquestion_question_asked_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='negative_feedback_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='positive_feedback_count',
            field=models.IntegerField(default=0),
        ),
    ]
