# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ai_api.models.job_instance_out import JobInstanceOut

class TestJobInstanceOut(unittest.TestCase):
    """JobInstanceOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobInstanceOut:
        """Test JobInstanceOut
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobInstanceOut`
        """
        model = JobInstanceOut()
        if include_optional:
            return JobInstanceOut(
                id = 56,
                name = '',
                job_name = '',
                repository_url = '',
                starting_commit = '',
                cluster_name = '',
                userlogin = '',
                status = '',
                started_at = '',
                finished_at = None,
                cluster = ai_api.models.cluster_out.ClusterOut(
                    name = '', 
                    userlogin = '', 
                    provider = ai_api.models.provider_out.ProviderOut(
                        id = 56, 
                        name = '', 
                        provider_type = ai_api.models.provider_type_out.ProviderTypeOut(
                            id = 56, 
                            name = '', 
                            module = '', ), ), )
            )
        else:
            return JobInstanceOut(
                id = 56,
                name = '',
                job_name = '',
                repository_url = '',
                starting_commit = '',
                cluster_name = '',
                userlogin = '',
                status = '',
                started_at = '',
                cluster = ai_api.models.cluster_out.ClusterOut(
                    name = '', 
                    userlogin = '', 
                    provider = ai_api.models.provider_out.ProviderOut(
                        id = 56, 
                        name = '', 
                        provider_type = ai_api.models.provider_type_out.ProviderTypeOut(
                            id = 56, 
                            name = '', 
                            module = '', ), ), ),
        )
        """

    def testJobInstanceOut(self):
        """Test JobInstanceOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
