# Generated by Django 4.2.5 on 2024-01-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="session_key",
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
