# Generated by Django 5.0.3 on 2024-03-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_uploadedfile_name_uploadedfile_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=255)),
                ('bot_answer', models.TextField()),
                ('is_helpful', models.BooleanField(default=False)),
                ('additional_comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
