# Generated by Django 5.0.3 on 2024-04-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_chatsession_session_id_alter_chatsession_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='id',
            new_name='session_id',
        ),
    ]
