# Generated by Django 5.0.3 on 2024-04-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_uploadedfile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='chatbot_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='chatbot_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
