# coding: utf-8

"""
    AIForged API

    Integration with AI Forged system  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: support@aiforged.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.doc_status2 import DocStatus2  # noqa: E501
from swagger_client.rest import ApiException


class TestDocStatus2(unittest.TestCase):
    """DocStatus2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocStatus2(self):
        """Test DocStatus2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.doc_status2.DocStatus2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
