# coding: utf-8

"""
    AIForged API

    Integration with AI Forged system  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: support@aiforged.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ai_forged_view_models_group_role_view_model import AIForgedViewModelsGroupRoleViewModel  # noqa: E501
from swagger_client.rest import ApiException


class TestAIForgedViewModelsGroupRoleViewModel(unittest.TestCase):
    """AIForgedViewModelsGroupRoleViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAIForgedViewModelsGroupRoleViewModel(self):
        """Test AIForgedViewModelsGroupRoleViewModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ai_forged_view_models_group_role_view_model.AIForgedViewModelsGroupRoleViewModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
