# coding: utf-8

"""
    AIForged API

    Integration with AI Forged system  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: support@aiforged.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ai_forged_dal_group_role_status import AIForgedDALGroupRoleStatus  # noqa: E501
from swagger_client.rest import ApiException


class TestAIForgedDALGroupRoleStatus(unittest.TestCase):
    """AIForgedDALGroupRoleStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAIForgedDALGroupRoleStatus(self):
        """Test AIForgedDALGroupRoleStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ai_forged_dal_group_role_status.AIForgedDALGroupRoleStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
